import Link from "next/link";
import { contactConfig, whatsappHref } from "@/lib/contact-config";
import { nav, services } from "@/lib/site-data";

export function Header(){return <header className="header"><Link className="brand" href="/"><span className="mark">PA</span><span>Piscines Aiguadolç</span></Link><nav>{nav.map(([n,h])=><Link key={h} href={h}>{n}</Link>)}</nav><div className="headCtas"><a href={whatsappHref()} className="ghost">WhatsApp</a><Link href="/presupuesto-piscina-sitges" className="btn small">Presupuesto</Link></div></header>}
export function Footer(){return <footer className="footer"><div><b>Piscines Aiguadolç</b><p>Construcción y reforma de piscinas en Sitges i rodalies.</p></div><div><p><a href={contactConfig.phoneHref}>{contactConfig.phoneDisplay}</a></p><p><a href={`mailto:${contactConfig.email}`}>{contactConfig.email}</a></p><p>{contactConfig.serviceArea}</p></div><div><Link href="/politica-privacidad">Privacidad</Link><Link href="/aviso-legal">Aviso legal</Link></div></footer>}
export function Ctas(){return <div className="ctas"><Link className="btn" href="/presupuesto-piscina-sitges">Solicitar presupuesto</Link><a className="btn alt" href={whatsappHref()}>WhatsApp</a><a className="ghost" href={contactConfig.phoneHref}>Llamar</a></div>}
export function ContactForm(){return <form className="form" action={`mailto:${contactConfig.email}`} method="post" encType="text/plain"><input type="hidden" name="asunto" value={contactConfig.leadSubject}/>{[["nombre","Nombre"],["telefono","Teléfono"],["email","Email"],["zona","Zona"]].map(([id,label])=><label key={id}>{label}<input name={id} id={id} required={id!=="email"}/></label>)}<label>Tipo de servicio<select name="tipo de servicio" defaultValue=""><option value="" disabled>Selecciona una opción</option><option>Construcción de piscina</option><option>Reforma de piscina</option><option>Renovación de acabados</option><option>Diseño exterior con piscina</option></select></label><label>Construcción o reforma<select name="construcción o reforma"><option>Construcción</option><option>Reforma</option><option>No lo tengo claro</option></select></label><label>Estado actual de la piscina si existe<input name="estado actual"/></label><label>Plazo aproximado<input name="plazo"/></label><label>Mensaje<textarea name="mensaje" rows={5} required/></label><button className="btn" type="submit">Enviar solicitud</button><p className="micro">El formulario abre tu cliente de correo con destino a {contactConfig.email} y asunto “{contactConfig.leadSubject}”.</p></form>}
export function ServiceGrid(){return <div className="grid">{services.map(([t,h,d])=><Link className="card" href={h} key={h}><span>{t}</span><p>{d}</p></Link>)}</div>}
export function JsonLd({data}:{data:object}){return <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(data)}}/>}
